#!/usr/bin/env python3
"""ServoHub CANopen/CiA402 code-generation entry point.

The CanFestival object-dictionary generator remains upstream (objdictgen/odg).
This wrapper pins ServoHub paths/configuration and adds deterministic CiA402
index/header/document generation without modifying upstream gen_cfile.py.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any


HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
DEFAULT_CONFIG = HERE / "codegen.json"


def _load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fp:
        return json.load(fp)


def _repo_path(value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else REPO_ROOT / path


def _find_odg() -> str:
    override = os.environ.get("SERVOHUB_ODG")
    if override:
        return override

    candidates = [
        HERE / ".venv" / "Scripts" / "odg.exe",
        HERE / ".venv" / "bin" / "odg",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return str(candidate)

    discovered = shutil.which("odg")
    if discovered:
        return discovered

    raise RuntimeError(
        "odg was not found. Run tools/canopen_codegen/setup.ps1 on Windows "
        "or tools/canopen_codegen/setup.sh on Linux/macOS, or set SERVOHUB_ODG."
    )


def _run(args: list[str]) -> None:
    print("+", " ".join(args))
    subprocess.run(args, cwd=REPO_ROOT, check=True)


def _symbol(name: str) -> str:
    chars = []
    previous_underscore = False
    for ch in name.upper():
        if ch.isalnum():
            chars.append(ch)
            previous_underscore = False
        elif not previous_underscore:
            chars.append("_")
            previous_underscore = True
    return "".join(chars).strip("_")


def _render_profile_header(profile: dict[str, Any]) -> str:
    guard = "SERVOHUB_CIA402_OD_GENERATED_H"
    lines = [
        "/* Auto-generated by tools/canopen_codegen/generate.py. Do not edit. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct",
        "{",
        "    uint16_t index;",
        "    uint8_t subindex;",
        "} cia402_od_address_t;",
        "",
    ]

    for item in profile["objects"]:
        symbol = _symbol(item["name"])
        index = int(item["index"], 0)
        subindex = int(item.get("subindex", 0))
        lines.extend(
            [
                f"#define CIA402_OD_{symbol}_INDEX ((uint16_t)0x{index:04X}u)",
                f"#define CIA402_OD_{symbol}_SUBINDEX ((uint8_t)0x{subindex:02X}u)",
                "",
            ]
        )

    lines.extend(
        [
            "typedef enum",
            "{",
        ]
    )
    for name, value in profile.get("modes_of_operation", {}).items():
        lines.append(f"    CIA402_MODE_{_symbol(name)} = {int(value)},")
    lines.extend(
        [
            "} cia402_mode_of_operation_t;",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )
    return "\n".join(lines)


def _render_profile_doc(profile: dict[str, Any]) -> str:
    lines = [
        "# ServoHub CiA 402 object dictionary contract",
        "",
        "> Auto-generated by `tools/canopen_codegen/generate.py`. Do not edit.",
        "",
        "| Index | Sub | Name | C type | Access | PDO | Unit |",
        "|---:|---:|---|---|---|---|---|",
    ]
    for item in profile["objects"]:
        index = int(item["index"], 0)
        subindex = int(item.get("subindex", 0))
        lines.append(
            f"| `0x{index:04X}` | `0x{subindex:02X}` | {item['name']} | "
            f"`{item['c_type']}` | {item['access']} | {item.get('pdo', '-')} | "
            f"{item.get('unit', '-')} |"
        )
    lines.extend(
        [
            "",
            "## Rules",
            "",
            "- The EDS/JSONC object dictionary is the protocol source of truth.",
            "- This profile is the ServoHub typed contract used by application code and reviews.",
            "- Generated CanFestival `SlaveOD.c/.h` must not be edited manually.",
            "- Changing an index, sub-index, signedness, or PDO direction is an interface change.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_profile_outputs(config: dict[str, Any]) -> None:
    profile_path = _repo_path(config["cia402"]["profile"])
    profile = _load_json(profile_path)

    header_path = _repo_path(config["cia402"]["output_header"])
    doc_path = _repo_path(config["cia402"]["output_doc"])
    header_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.parent.mkdir(parents=True, exist_ok=True)

    with header_path.open("w", encoding="utf-8", newline="\n") as fp:
        fp.write(_render_profile_header(profile))
    with doc_path.open("w", encoding="utf-8", newline="\n") as fp:
        fp.write(_render_profile_doc(profile))
    print(f"generated {header_path.relative_to(REPO_ROOT)}")
    print(f"generated {doc_path.relative_to(REPO_ROOT)}")


def _generate_canopen(config: dict[str, Any]) -> None:
    odg = _find_odg()
    source = _repo_path(config["object_dictionary"]["source"])
    output_c = _repo_path(config["object_dictionary"]["output_c"])
    output_c.parent.mkdir(parents=True, exist_ok=True)
    _run([odg, "convert", str(source), str(output_c)])


def _validate_canopen(config: dict[str, Any]) -> None:
    odg = _find_odg()
    source = _repo_path(config["object_dictionary"]["source"])
    _run([odg, "list", str(source)])


def _check_profile_outputs(config: dict[str, Any]) -> bool:
    profile = _load_json(_repo_path(config["cia402"]["profile"]))
    expected = {
        _repo_path(config["cia402"]["output_header"]): _render_profile_header(profile),
        _repo_path(config["cia402"]["output_doc"]): _render_profile_doc(profile),
    }
    ok = True
    for path, content in expected.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != content:
            print(f"stale generated file: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            ok = False
    return ok


def _migrate_jsonc(config: dict[str, Any]) -> None:
    odg = _find_odg()
    source = _repo_path(config["object_dictionary"]["source"])
    destination = _repo_path(config["object_dictionary"]["jsonc_migration_target"])
    destination.parent.mkdir(parents=True, exist_ok=True)
    _run([odg, "convert", str(source), str(destination)])
    print(
        "JSONC migration created. Review the diff, then set "
        "'object_dictionary.source' in codegen.json to the JSONC file."
    )


def _doctor(config: dict[str, Any]) -> None:
    print(f"repo root : {REPO_ROOT}")
    print(f"config    : {DEFAULT_CONFIG}")
    print(f"source    : {_repo_path(config['object_dictionary']['source'])}")
    print(f"output C  : {_repo_path(config['object_dictionary']['output_c'])}")
    print(f"profile   : {_repo_path(config['cia402']['profile'])}")
    print(f"odg       : {_find_odg()}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help="Path to ServoHub codegen JSON configuration.",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("doctor", help="Show resolved paths and odg executable.")
    sub.add_parser("list", help="Parse and list the configured object dictionary.")
    sub.add_parser("generate", help="Regenerate CanFestival C/H and CiA402 contract outputs.")
    sub.add_parser("generate-profile", help="Regenerate only CiA402 typed header/docs.")
    sub.add_parser("check", help="Validate OD parsing and checked-in typed outputs.")
    sub.add_parser("migrate-jsonc", help="Create the initial JSONC copy from the current EDS.")

    args = parser.parse_args()
    config_path = args.config if args.config.is_absolute() else REPO_ROOT / args.config
    config = _load_json(config_path)

    try:
        if args.command == "doctor":
            _doctor(config)
        elif args.command == "list":
            _validate_canopen(config)
        elif args.command == "generate":
            _generate_canopen(config)
            _write_profile_outputs(config)
        elif args.command == "generate-profile":
            _write_profile_outputs(config)
        elif args.command == "check":
            _validate_canopen(config)
            if not _check_profile_outputs(config):
                print(
                    "Run 'python tools/canopen_codegen/generate.py generate-profile' "
                    "and commit the result.",
                    file=sys.stderr,
                )
                return 2
        elif args.command == "migrate-jsonc":
            _migrate_jsonc(config)
    except (OSError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
