
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SLAVEOD_H
#define SLAVEOD_H

#include "data.h"
#include "drv_can_app.h"

/* Prototypes of function provided by object dictionnary */
UNS32 SlaveOD_valueRangeTest (UNS8 typeValue, void * value);
const indextable * SlaveOD_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data SlaveOD_Data;
extern UNS16 ErrorCode;		/* Mapped at index 0x603F, subindex 0x00*/
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/
extern INTEGER16 Quick_stop_option_code;		/* Mapped at index 0x605A, subindex 0x00*/
extern INTEGER8 Modes_of_operation;		/* Mapped at index 0x6060, subindex 0x00*/
extern INTEGER8 Modes_of_operation_display;		/* Mapped at index 0x6061, subindex 0x00*/
extern INTEGER32 Position_demannd_value;		/* Mapped at index 0x6062, subindex 0x00*/
extern INTEGER32 Motor_Position_actual_value;		/* Mapped at index 0x6063, subindex 0x00*/
extern INTEGER32 Position_actual_value;		/* Mapped at index 0x6064, subindex 0x00*/
extern UNS32 Following_error_window;		/* Mapped at index 0x6065, subindex 0x00*/
extern UNS16 Following_error_time_out;		/* Mapped at index 0x6066, subindex 0x00*/
extern UNS32 Position_window;		/* Mapped at index 0x6067, subindex 0x00*/
extern UNS16 Position_window_time;		/* Mapped at index 0x6068, subindex 0x00*/
extern INTEGER32 Velocity_demand_value;		/* Mapped at index 0x606B, subindex 0x00*/
extern INTEGER32 Velocity_actual_value;		/* Mapped at index 0x606C, subindex 0x00*/
extern UNS16 Velocity_window;		/* Mapped at index 0x606D, subindex 0x00*/
extern UNS16 Velocity_window_time;		/* Mapped at index 0x606E, subindex 0x00*/
extern UNS16 Velocity_threshold;		/* Mapped at index 0x606F, subindex 0x00*/
extern UNS16 Velocity_threshold_time;		/* Mapped at index 0x6070, subindex 0x00*/
extern INTEGER16 Target_torque;		/* Mapped at index 0x6071, subindex 0x00*/
extern UNS16 Max_torque;		/* Mapped at index 0x6072, subindex 0x00*/
extern UNS16 Max_current;		/* Mapped at index 0x6073, subindex 0x00*/
extern INTEGER16 Torque_demand_value;		/* Mapped at index 0x6074, subindex 0x00*/
extern UNS32 Motor_rated_current;		/* Mapped at index 0x6075, subindex 0x00*/
extern UNS32 Motor_rated_torque;		/* Mapped at index 0x6076, subindex 0x00*/
extern INTEGER16 Torque_actual_value;		/* Mapped at index 0x6077, subindex 0x00*/
extern INTEGER16 Current_actual_value;		/* Mapped at index 0x6078, subindex 0x00*/
extern UNS32 DC_link_circuit_voltage;		/* Mapped at index 0x6079, subindex 0x00*/
extern INTEGER32 Target_position;		/* Mapped at index 0x607A, subindex 0x00*/
extern INTEGER32 Position_range_limit_Minimal_position_limit;		/* Mapped at index 0x607B, subindex 0x01 */
extern INTEGER32 Position_range_limit_Maximal_position_limit;		/* Mapped at index 0x607B, subindex 0x02 */
extern INTEGER32 Home_offset;		/* Mapped at index 0x607C, subindex 0x00*/
extern INTEGER32 Software_position_limit_Minimal_position_limit;		/* Mapped at index 0x607D, subindex 0x01 */
extern INTEGER32 Software_position_limit_Maximal_position_limit;		/* Mapped at index 0x607D, subindex 0x02 */
extern UNS8 Polarity;		/* Mapped at index 0x607E, subindex 0x00*/
extern UNS32 Maximal_profile_velocity;		/* Mapped at index 0x607F, subindex 0x00*/
extern UNS32 Max_motor_speed;		/* Mapped at index 0x6080, subindex 0x00*/
extern UNS32 Profile_velocity;		/* Mapped at index 0x6081, subindex 0x00*/
extern UNS32 Profile_acceleration;		/* Mapped at index 0x6083, subindex 0x00*/
extern UNS32 Profile_deceleration;		/* Mapped at index 0x6084, subindex 0x00*/
extern UNS32 Quick_stop_deceleration;		/* Mapped at index 0x6085, subindex 0x00*/
extern UNS32 Torque_slope;		/* Mapped at index 0x6087, subindex 0x00*/
extern UNS32 Position_encoder_resolution_Encoder_increments;		/* Mapped at index 0x608F, subindex 0x01 */
extern UNS32 Position_encoder_resolution_Motor_revolutions;		/* Mapped at index 0x608F, subindex 0x02 */
extern UNS32 Gear_ratio_Motor_revolutions;		/* Mapped at index 0x6091, subindex 0x01 */
extern UNS32 Gear_ratio_Shaft_revolutions;		/* Mapped at index 0x6091, subindex 0x02 */
extern INTEGER8 Homing_method;		/* Mapped at index 0x6098, subindex 0x00*/
extern INTEGER32 Position_offset;		/* Mapped at index 0x60B0, subindex 0x00*/
extern INTEGER32 Velocity_offset;		/* Mapped at index 0x60B1, subindex 0x00*/
extern INTEGER16 Torque_offset;		/* Mapped at index 0x60B2, subindex 0x00*/
extern UNS8 Interpolation_time_period_Interpolation_time_period_Ip_time_units;		/* Mapped at index 0x60C2, subindex 0x01 */
extern INTEGER8 Interpolation_time_period_Interpolation_time_period_Ip_time_index;		/* Mapped at index 0x60C2, subindex 0x02 */
extern UNS32 Max_acceleration;		/* Mapped at index 0x60C5, subindex 0x00*/
extern UNS32 Max_deceleration;		/* Mapped at index 0x60C6, subindex 0x00*/
extern INTEGER32 Following_error_actual_value;		/* Mapped at index 0x60F4, subindex 0x00*/
extern UNS32 Digital_inputs;		/* Mapped at index 0x60FD, subindex 0x00*/
extern UNS32 Digital_outputs_Digital_outputs_Physical_outputs;		/* Mapped at index 0x60FE, subindex 0x01 */
extern UNS32 Digital_outputs_Digital_outputs_Bit_mask;		/* Mapped at index 0x60FE, subindex 0x02 */
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/

#endif // SLAVEOD_H
