
/* File generated by gen_cfile.py. Should not be modified. */

#include "SlaveOD.h"
//由于定义冲突，objdictdef.h文件部分宏定义移动到SlaveOD.c文件中
#define boolean         0x01
#define int8            0x02
#define int16           0x03
#define int32           0x04
#define uint8           0x05
#define uint16          0x06
#define uint32          0x07


/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 ErrorCode = 0x0;		/* Mapped at index 0x603F, subindex 0x00 */
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER16 Quick_stop_option_code = 0x0;		/* Mapped at index 0x605A, subindex 0x00 */
INTEGER8 Modes_of_operation = 0x0;		/* Mapped at index 0x6060, subindex 0x00 */
INTEGER8 Modes_of_operation_display = 0x0;		/* Mapped at index 0x6061, subindex 0x00 */
INTEGER32 Position_demannd_value = 0x0;		/* Mapped at index 0x6062, subindex 0x00 */
INTEGER32 Motor_Position_actual_value = 0x0;		/* Mapped at index 0x6063, subindex 0x00 */
INTEGER32 Position_actual_value = 0x0;		/* Mapped at index 0x6064, subindex 0x00 */
UNS32 Following_error_window = 0x0;		/* Mapped at index 0x6065, subindex 0x00 */
UNS16 Following_error_time_out = 0x0;		/* Mapped at index 0x6066, subindex 0x00 */
UNS32 Position_window = 0x0;		/* Mapped at index 0x6067, subindex 0x00 */
UNS16 Position_window_time = 0x0;		/* Mapped at index 0x6068, subindex 0x00 */
INTEGER32 Velocity_sensor_actual_value = 0x0;		/* Mapped at index 0x6069, subindex 0x00 */
INTEGER32 Velocity_demand_value = 0x0;		/* Mapped at index 0x606B, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
UNS16 Velocity_window = 0x0;		/* Mapped at index 0x606D, subindex 0x00 */
UNS16 Velocity_window_time = 0x0;		/* Mapped at index 0x606E, subindex 0x00 */
UNS16 Velocity_threshold = 0x0;		/* Mapped at index 0x606F, subindex 0x00 */
UNS16 Velocity_threshold_time = 0x0;		/* Mapped at index 0x6070, subindex 0x00 */
INTEGER16 Target_torque = 0x0;		/* Mapped at index 0x6071, subindex 0x00 */
UNS16 Max_torque = 0x0;		/* Mapped at index 0x6072, subindex 0x00 */
UNS16 Max_current = 0x0;		/* Mapped at index 0x6073, subindex 0x00 */
INTEGER16 Torque_demand_value = 0x0;		/* Mapped at index 0x6074, subindex 0x00 */
UNS32 Motor_rated_current = 0x0;		/* Mapped at index 0x6075, subindex 0x00 */
UNS32 Motor_rated_torque = 0x0;		/* Mapped at index 0x6076, subindex 0x00 */
INTEGER16 Torque_actual_value = 0x0;		/* Mapped at index 0x6077, subindex 0x00 */
INTEGER16 Current_actual_value = 0x0;		/* Mapped at index 0x6078, subindex 0x00 */
UNS32 DC_link_circuit_voltage = 0x0;		/* Mapped at index 0x6079, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
INTEGER32 Position_range_limit_Minimal_position_limit = 0x0;		/* Mapped at index 0x607B, subindex 0x01 */
INTEGER32 Position_range_limit_Maximal_position_limit = 0x0;		/* Mapped at index 0x607B, subindex 0x02 */
INTEGER32 Home_offset = 0x0;		/* Mapped at index 0x607C, subindex 0x00 */
INTEGER32 Software_position_limit_Minimal_position_limit = 0x0;		/* Mapped at index 0x607D, subindex 0x01 */
INTEGER32 Software_position_limit_Maximal_position_limit = 0x0;		/* Mapped at index 0x607D, subindex 0x02 */
UNS8 Polarity = 0x0;		/* Mapped at index 0x607E, subindex 0x00 */
UNS32 Maximal_profile_velocity = 0x0;		/* Mapped at index 0x607F, subindex 0x00 */
UNS32 Max_motor_speed = 0x0;		/* Mapped at index 0x6080, subindex 0x00 */
UNS32 Profile_velocity = 0x0;		/* Mapped at index 0x6081, subindex 0x00 */
UNS32 Profile_acceleration = 0x0;		/* Mapped at index 0x6083, subindex 0x00 */
UNS32 Profile_deceleration = 0x0;		/* Mapped at index 0x6084, subindex 0x00 */
UNS32 Quick_stop_deceleration = 0x0;		/* Mapped at index 0x6085, subindex 0x00 */
INTEGER16 Motion_profile_type = 0x0;		/* Mapped at index 0x6086, subindex 0x00 */
UNS32 Torque_slope = 0x0;		/* Mapped at index 0x6087, subindex 0x00 */
INTEGER8 Position_notation_index = 0x0;		/* Mapped at index 0x6089, subindex 0x00 */
REAL32 Position_dimention_index = 0.000000;		/* Mapped at index 0x608A, subindex 0x00 */
INTEGER8 Velocity_notation_index = 0x0;		/* Mapped at index 0x608B, subindex 0x00 */
REAL32 Velocity_dimention_index = 0.000000;		/* Mapped at index 0x608C, subindex 0x00 */
INTEGER8 Acceleraion_notation_index = 0x0;		/* Mapped at index 0x608D, subindex 0x00 */
REAL32 Acceleraion_dimention_index = 0.000000;		/* Mapped at index 0x608E, subindex 0x00 */
UNS32 Position_encoder_resolution_Encoder_increments = 0x0;		/* Mapped at index 0x608F, subindex 0x01 */
UNS32 Position_encoder_resolution_Motor_revolutions = 0x0;		/* Mapped at index 0x608F, subindex 0x02 */
UNS32 Gear_ratio_Motor_revolutions = 0x0;		/* Mapped at index 0x6091, subindex 0x01 */
UNS32 Gear_ratio_Shaft_revolutions = 0x0;		/* Mapped at index 0x6091, subindex 0x02 */
INTEGER8 Homing_method = 0x0;		/* Mapped at index 0x6098, subindex 0x00 */
UNS32 Homing_speeds_Speed_for_switch_search = 0x0;		/* Mapped at index 0x6099, subindex 0x01 */
UNS32 Homing_speeds_Speed_for_zero_search = 0x0;		/* Mapped at index 0x6099, subindex 0x02 */
UNS32 Homing_acceleration = 0x0;		/* Mapped at index 0x609A, subindex 0x00 */
INTEGER32 Position_offset = 0x0;		/* Mapped at index 0x60B0, subindex 0x00 */
INTEGER32 Velocity_offset = 0x0;		/* Mapped at index 0x60B1, subindex 0x00 */
INTEGER16 Torque_offset = 0x0;		/* Mapped at index 0x60B2, subindex 0x00 */
UNS8 Interpolation_time_period_Interpolation_time_period_Ip_time_units = 0x1;		/* Mapped at index 0x60C2, subindex 0x01 */
INTEGER8 Interpolation_time_period_Interpolation_time_period_Ip_time_index = 0xFD;		/* Mapped at index 0x60C2, subindex 0x02 */
UNS32 Max_acceleration = 0x0;		/* Mapped at index 0x60C5, subindex 0x00 */
UNS32 Max_deceleration = 0x0;		/* Mapped at index 0x60C6, subindex 0x00 */
INTEGER32 Following_error_actual_value = 0x0;		/* Mapped at index 0x60F4, subindex 0x00 */
INTEGER16 Current_control_parameter_set_Current_regulator_P_gain = 0x0;		/* Mapped at index 0x60F6, subindex 0x01 */
INTEGER16 Current_control_parameter_set_Current_regulator_I_gain = 0x0;		/* Mapped at index 0x60F6, subindex 0x02 */
INTEGER16 Velocity_control_parameter_set_Velocity_regulator_P_gain = 0x0;		/* Mapped at index 0x60F9, subindex 0x01 */
INTEGER16 Velocity_control_parameter_set_Velocity_regulator_I_gain = 0x0;		/* Mapped at index 0x60F9, subindex 0x02 */
INTEGER16 Position_control_parameter_set_Position_regulator_P_gain = 0x0;		/* Mapped at index 0x60FB, subindex 0x01 */
INTEGER16 Position_control_parameter_set_Position_regulator_I_gain = 0x0;		/* Mapped at index 0x60FB, subindex 0x02 */
INTEGER16 Position_control_parameter_set_Position_regulator_D_gain = 0x0;		/* Mapped at index 0x60FB, subindex 0x03 */
UNS16 Position_control_parameter_set_Velocity_feed_forward_factor = 0x0;		/* Mapped at index 0x60FB, subindex 0x04 */
UNS16 Position_control_parameter_set_Acceleration_feed_forward_factor = 0x0;		/* Mapped at index 0x60FB, subindex 0x05 */
UNS32 Digital_inputs = 0x0;		/* Mapped at index 0x60FD, subindex 0x00 */
UNS32 Digital_outputs_Digital_outputs_Physical_outputs = 0x0;		/* Mapped at index 0x60FE, subindex 0x01 */
UNS32 Digital_outputs_Digital_outputs_Bit_mask = 0x0;		/* Mapped at index 0x60FE, subindex 0x02 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */
UNS16 Motor_type = 0x0;		/* Mapped at index 0x6402, subindex 0x00 */
UNS16 Motor_data_Continous_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x01 */
UNS16 Motor_data_Output_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x02 */
UNS8 Motor_data_Pole_pair_number = 0x0;		/* Mapped at index 0x6410, subindex 0x03 */
UNS16 Motor_data_Maximal_speed_in_current_mode = 0x0;		/* Mapped at index 0x6410, subindex 0x04 */
UNS16 Motor_data_Thermal_time_constant_winding = 0x0;		/* Mapped at index 0x6410, subindex 0x05 */
UNS32 Supported_drive_modes = 0x0;		/* Mapped at index 0x6502, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 SlaveOD_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 SlaveOD_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 SlaveOD_iam_a_slave = 1;

TIMER_HANDLE SlaveOD_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 SlaveOD_obj1000 = 0x20192;	/* 131474 */
                    subindex SlaveOD_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 SlaveOD_obj1001 = 0x0;	/* 0 */
                    subindex SlaveOD_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 SlaveOD_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 SlaveOD_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 SlaveOD_obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 SlaveOD_obj1008[10] = "YuanHunb";
                    subindex SlaveOD_Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&SlaveOD_obj1008, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 SlaveOD_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 SlaveOD_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 SlaveOD_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 SlaveOD_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1016[0], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 SlaveOD_obj1017 = 0x64;	/* 100 */
                    subindex SlaveOD_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 SlaveOD_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 SlaveOD_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 SlaveOD_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 SlaveOD_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex SlaveOD_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 SlaveOD_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 SlaveOD_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex SlaveOD_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 SlaveOD_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 SlaveOD_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex SlaveOD_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 SlaveOD_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 SlaveOD_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex SlaveOD_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 SlaveOD_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 SlaveOD_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex SlaveOD_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 SlaveOD_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 SlaveOD_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex SlaveOD_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 SlaveOD_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1600[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1600[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1600[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1600[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1600[7], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 SlaveOD_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1601[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1601[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1601[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1601[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1601[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1601[7], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 SlaveOD_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1602[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1602[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1602[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1602[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1602[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1602[7], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 SlaveOD_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1603[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1603[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1603[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1603[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1603[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1603[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1603[7], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 SlaveOD_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 SlaveOD_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex SlaveOD_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 SlaveOD_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 SlaveOD_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex SlaveOD_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 SlaveOD_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 SlaveOD_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex SlaveOD_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 SlaveOD_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 SlaveOD_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SlaveOD_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 SlaveOD_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex SlaveOD_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SlaveOD_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 SlaveOD_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A00[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A00[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A00[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A00[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A00[7], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 SlaveOD_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A01[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A01[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A01[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A01[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A01[7], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 SlaveOD_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A02[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A02[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A02[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A02[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A02[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A02[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A02[7], NULL }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 SlaveOD_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 SlaveOD_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SlaveOD_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj1A03, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A03[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A03[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A03[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A03[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A03[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A03[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A03[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SlaveOD_obj1A03[7], NULL }
                     };

/* index 0x603F :   Mapped variable ErrorCode */
                    subindex SlaveOD_Index603F[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&ErrorCode, NULL }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex SlaveOD_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword, NULL }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    subindex SlaveOD_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword, NULL }
                     };

/* index 0x605A :   Mapped variable Quick stop option code */
                    subindex SlaveOD_Index605A[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Quick_stop_option_code, NULL }
                     };

/* index 0x6060 :   Mapped variable Modes of operation */
                    subindex SlaveOD_Index6060[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Modes_of_operation, NULL }
                     };

/* index 0x6061 :   Mapped variable Modes of operation display */
                    subindex SlaveOD_Index6061[] = 
                     {
                       { RO, int8, sizeof (INTEGER8), (void*)&Modes_of_operation_display, NULL }
                     };

/* index 0x6062 :   Mapped variable Position demannd value */
                    subindex SlaveOD_Index6062[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_demannd_value, NULL }
                     };

/* index 0x6063 :   Mapped variable Motor Position actual value */
                    subindex SlaveOD_Index6063[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Motor_Position_actual_value, NULL }
                     };

/* index 0x6064 :   Mapped variable Position actual value */
                    subindex SlaveOD_Index6064[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_actual_value, NULL }
                     };

/* index 0x6065 :   Mapped variable Following error window */
                    subindex SlaveOD_Index6065[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Following_error_window, NULL }
                     };

/* index 0x6066 :   Mapped variable Following error time out */
                    subindex SlaveOD_Index6066[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Following_error_time_out, NULL }
                     };

/* index 0x6067 :   Mapped variable Position window */
                    subindex SlaveOD_Index6067[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Position_window, NULL }
                     };

/* index 0x6068 :   Mapped variable Position window time */
                    subindex SlaveOD_Index6068[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Position_window_time, NULL }
                     };

/* index 0x6069 :   Mapped variable Velocity sensor actual value */
                    subindex SlaveOD_Index6069[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_sensor_actual_value, NULL }
                     };

/* index 0x606B :   Mapped variable Velocity demand value */
                    subindex SlaveOD_Index606B[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_demand_value, NULL }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex SlaveOD_Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value, NULL }
                     };

/* index 0x606D :   Mapped variable Velocity window */
                    subindex SlaveOD_Index606D[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Velocity_window, NULL }
                     };

/* index 0x606E :   Mapped variable Velocity window time */
                    subindex SlaveOD_Index606E[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Velocity_window_time, NULL }
                     };

/* index 0x606F :   Mapped variable Velocity threshold */
                    subindex SlaveOD_Index606F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Velocity_threshold, NULL }
                     };

/* index 0x6070 :   Mapped variable Velocity threshold  time */
                    subindex SlaveOD_Index6070[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Velocity_threshold_time, NULL }
                     };

/* index 0x6071 :   Mapped variable Target torque */
                    subindex SlaveOD_Index6071[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Target_torque, NULL }
                     };

/* index 0x6072 :   Mapped variable Max torque */
                    subindex SlaveOD_Index6072[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Max_torque, NULL }
                     };

/* index 0x6073 :   Mapped variable Max current */
                    subindex SlaveOD_Index6073[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Max_current, NULL }
                     };

/* index 0x6074 :   Mapped variable Torque demand value */
                    subindex SlaveOD_Index6074[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Torque_demand_value, NULL }
                     };

/* index 0x6075 :   Mapped variable Motor rated current */
                    subindex SlaveOD_Index6075[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_rated_current, NULL }
                     };

/* index 0x6076 :   Mapped variable Motor rated torque */
                    subindex SlaveOD_Index6076[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_rated_torque, NULL }
                     };

/* index 0x6077 :   Mapped variable Torque actual value */
                    subindex SlaveOD_Index6077[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Torque_actual_value, NULL }
                     };

/* index 0x6078 :   Mapped variable Current actual value */
                    subindex SlaveOD_Index6078[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Current_actual_value, NULL }
                     };

/* index 0x6079 :   Mapped variable DC link circuit voltage */
                    subindex SlaveOD_Index6079[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&DC_link_circuit_voltage, NULL }
                     };

/* index 0x607A :   Mapped variable Target position */
                    subindex SlaveOD_Index607A[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_position, NULL }
                     };

/* index 0x607B :   Mapped variable Position range limit */
                    UNS8 SlaveOD_highestSubIndex_obj607B = 2; /* number of subindex - 1*/
                    subindex SlaveOD_Index607B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj607B, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&Position_range_limit_Minimal_position_limit, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&Position_range_limit_Maximal_position_limit, NULL }
                     };

/* index 0x607C :   Mapped variable Home offset */
                    subindex SlaveOD_Index607C[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Home_offset, NULL }
                     };

/* index 0x607D :   Mapped variable Software position limit */
                    UNS8 SlaveOD_highestSubIndex_obj607D = 2; /* number of subindex - 1*/
                    subindex SlaveOD_Index607D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj607D, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&Software_position_limit_Minimal_position_limit, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&Software_position_limit_Maximal_position_limit, NULL }
                     };

/* index 0x607E :   Mapped variable Polarity */
                    subindex SlaveOD_Index607E[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Polarity, NULL }
                     };

/* index 0x607F :   Mapped variable Maximal profile velocity */
                    subindex SlaveOD_Index607F[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Maximal_profile_velocity, NULL }
                     };

/* index 0x6080 :   Mapped variable Max motor speed */
                    subindex SlaveOD_Index6080[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Max_motor_speed, NULL }
                     };

/* index 0x6081 :   Mapped variable Profile velocity */
                    subindex SlaveOD_Index6081[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_velocity, NULL }
                     };

/* index 0x6083 :   Mapped variable Profile acceleration */
                    subindex SlaveOD_Index6083[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_acceleration, NULL }
                     };

/* index 0x6084 :   Mapped variable Profile deceleration */
                    subindex SlaveOD_Index6084[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_deceleration, NULL }
                     };

/* index 0x6085 :   Mapped variable Quick stop deceleration */
                    subindex SlaveOD_Index6085[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Quick_stop_deceleration, NULL }
                     };

/* index 0x6086 :   Mapped variable Motion profile type */
                    subindex SlaveOD_Index6086[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Motion_profile_type, NULL }
                     };

/* index 0x6087 :   Mapped variable Torque slope */
                    subindex SlaveOD_Index6087[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Torque_slope, NULL }
                     };

/* index 0x6089 :   Mapped variable Position notation index */
                    subindex SlaveOD_Index6089[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Position_notation_index, NULL }
                     };

/* index 0x608A :   Mapped variable Position dimention index */
                    subindex SlaveOD_Index608A[] = 
                     {
                       { RW, real32, sizeof (REAL32), (void*)&Position_dimention_index, NULL }
                     };

/* index 0x608B :   Mapped variable Velocity notation index */
                    subindex SlaveOD_Index608B[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Velocity_notation_index, NULL }
                     };

/* index 0x608C :   Mapped variable Velocity dimention index */
                    subindex SlaveOD_Index608C[] = 
                     {
                       { RW, real32, sizeof (REAL32), (void*)&Velocity_dimention_index, NULL }
                     };

/* index 0x608D :   Mapped variable Acceleraion notation index */
                    subindex SlaveOD_Index608D[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Acceleraion_notation_index, NULL }
                     };

/* index 0x608E :   Mapped variable Acceleraion dimention index */
                    subindex SlaveOD_Index608E[] = 
                     {
                       { RW, real32, sizeof (REAL32), (void*)&Acceleraion_dimention_index, NULL }
                     };

/* index 0x608F :   Mapped variable Position encoder resolution */
                    UNS8 SlaveOD_highestSubIndex_obj608F = 2; /* number of subindex - 1*/
                    subindex SlaveOD_Index608F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj608F, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_encoder_resolution_Encoder_increments, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Position_encoder_resolution_Motor_revolutions, NULL }
                     };

/* index 0x6091 :   Mapped variable Gear ratio */
                    UNS8 SlaveOD_highestSubIndex_obj6091 = 2; /* number of subindex - 1*/
                    subindex SlaveOD_Index6091[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj6091, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Gear_ratio_Motor_revolutions, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Gear_ratio_Shaft_revolutions, NULL }
                     };

/* index 0x6098 :   Mapped variable Homing method */
                    subindex SlaveOD_Index6098[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Homing_method, NULL }
                     };

/* index 0x6099 :   Mapped variable Homing speeds */
                    UNS8 SlaveOD_highestSubIndex_obj6099 = 2; /* number of subindex - 1*/
                    subindex SlaveOD_Index6099[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj6099, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_speeds_Speed_for_switch_search, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_speeds_Speed_for_zero_search, NULL }
                     };

/* index 0x609A :   Mapped variable Homing acceleration */
                    subindex SlaveOD_Index609A[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_acceleration, NULL }
                     };

/* index 0x60B0 :   Mapped variable Position offset */
                    subindex SlaveOD_Index60B0[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Position_offset, NULL }
                     };

/* index 0x60B1 :   Mapped variable Velocity offset */
                    subindex SlaveOD_Index60B1[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Velocity_offset, NULL }
                     };

/* index 0x60B2 :   Mapped variable Torque offset */
                    subindex SlaveOD_Index60B2[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Torque_offset, NULL }
                     };

/* index 0x60C2 :   Mapped variable Interpolation time period */
                    UNS8 SlaveOD_highestSubIndex_obj60C2 = 2; /* number of subindex - 1*/
                    subindex SlaveOD_Index60C2[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj60C2, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Interpolation_time_period_Interpolation_time_period_Ip_time_units, NULL },
                       { RW, int8, sizeof (INTEGER8), (void*)&Interpolation_time_period_Interpolation_time_period_Ip_time_index, NULL }
                     };

/* index 0x60C5 :   Mapped variable Max acceleration */
                    subindex SlaveOD_Index60C5[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Max_acceleration, NULL }
                     };

/* index 0x60C6 :   Mapped variable Max deceleration */
                    subindex SlaveOD_Index60C6[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Max_deceleration, NULL }
                     };

/* index 0x60F4 :   Mapped variable Following error actual value */
                    subindex SlaveOD_Index60F4[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Following_error_actual_value, NULL }
                     };

/* index 0x60F6 :   Mapped variable Current control parameter set */
                    UNS8 SlaveOD_highestSubIndex_obj60F6 = 2; /* number of subindex - 1*/
                    subindex SlaveOD_Index60F6[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj60F6, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Current_control_parameter_set_Current_regulator_P_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Current_control_parameter_set_Current_regulator_I_gain, NULL }
                     };

/* index 0x60F9 :   Mapped variable Velocity control parameter set */
                    UNS8 SlaveOD_highestSubIndex_obj60F9 = 2; /* number of subindex - 1*/
                    subindex SlaveOD_Index60F9[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj60F9, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Velocity_control_parameter_set_Velocity_regulator_P_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Velocity_control_parameter_set_Velocity_regulator_I_gain, NULL }
                     };

/* index 0x60FB :   Mapped variable Position control parameter set */
                    UNS8 SlaveOD_highestSubIndex_obj60FB = 5; /* number of subindex - 1*/
                    subindex SlaveOD_Index60FB[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj60FB, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Position_control_parameter_set_Position_regulator_P_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Position_control_parameter_set_Position_regulator_I_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Position_control_parameter_set_Position_regulator_D_gain, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Position_control_parameter_set_Velocity_feed_forward_factor, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Position_control_parameter_set_Acceleration_feed_forward_factor, NULL }
                     };

/* index 0x60FD :   Mapped variable Digital inputs */
                    subindex SlaveOD_Index60FD[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Digital_inputs, NULL }
                     };

/* index 0x60FE :   Mapped variable Digital outputs */
                    UNS8 SlaveOD_highestSubIndex_obj60FE = 2; /* number of subindex - 1*/
                    subindex SlaveOD_Index60FE[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj60FE, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Digital_outputs_Digital_outputs_Physical_outputs, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Digital_outputs_Digital_outputs_Bit_mask, NULL }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex SlaveOD_Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity, NULL }
                     };

/* index 0x6402 :   Mapped variable Motor type */
                    subindex SlaveOD_Index6402[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_type, NULL }
                     };

/* index 0x6410 :   Mapped variable Motor data */
                    UNS8 SlaveOD_highestSubIndex_obj6410 = 5; /* number of subindex - 1*/
                    subindex SlaveOD_Index6410[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&SlaveOD_highestSubIndex_obj6410, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Continous_current_limit, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Output_current_limit, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_data_Pole_pair_number, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Maximal_speed_in_current_mode, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Thermal_time_constant_winding, NULL }
                     };

/* index 0x6502 :   Mapped variable Supported drive modes */
                    subindex SlaveOD_Index6502[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Supported_drive_modes, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable SlaveOD_objdict[] = 
{
  { (subindex*)SlaveOD_Index1000,sizeof(SlaveOD_Index1000)/sizeof(SlaveOD_Index1000[0]), 0x1000},
  { (subindex*)SlaveOD_Index1001,sizeof(SlaveOD_Index1001)/sizeof(SlaveOD_Index1001[0]), 0x1001},
  { (subindex*)SlaveOD_Index1008,sizeof(SlaveOD_Index1008)/sizeof(SlaveOD_Index1008[0]), 0x1008},
  { (subindex*)SlaveOD_Index1016,sizeof(SlaveOD_Index1016)/sizeof(SlaveOD_Index1016[0]), 0x1016},
  { (subindex*)SlaveOD_Index1017,sizeof(SlaveOD_Index1017)/sizeof(SlaveOD_Index1017[0]), 0x1017},
  { (subindex*)SlaveOD_Index1018,sizeof(SlaveOD_Index1018)/sizeof(SlaveOD_Index1018[0]), 0x1018},
  { (subindex*)SlaveOD_Index1200,sizeof(SlaveOD_Index1200)/sizeof(SlaveOD_Index1200[0]), 0x1200},
  { (subindex*)SlaveOD_Index1400,sizeof(SlaveOD_Index1400)/sizeof(SlaveOD_Index1400[0]), 0x1400},
  { (subindex*)SlaveOD_Index1401,sizeof(SlaveOD_Index1401)/sizeof(SlaveOD_Index1401[0]), 0x1401},
  { (subindex*)SlaveOD_Index1402,sizeof(SlaveOD_Index1402)/sizeof(SlaveOD_Index1402[0]), 0x1402},
  { (subindex*)SlaveOD_Index1403,sizeof(SlaveOD_Index1403)/sizeof(SlaveOD_Index1403[0]), 0x1403},
  { (subindex*)SlaveOD_Index1600,sizeof(SlaveOD_Index1600)/sizeof(SlaveOD_Index1600[0]), 0x1600},
  { (subindex*)SlaveOD_Index1601,sizeof(SlaveOD_Index1601)/sizeof(SlaveOD_Index1601[0]), 0x1601},
  { (subindex*)SlaveOD_Index1602,sizeof(SlaveOD_Index1602)/sizeof(SlaveOD_Index1602[0]), 0x1602},
  { (subindex*)SlaveOD_Index1603,sizeof(SlaveOD_Index1603)/sizeof(SlaveOD_Index1603[0]), 0x1603},
  { (subindex*)SlaveOD_Index1800,sizeof(SlaveOD_Index1800)/sizeof(SlaveOD_Index1800[0]), 0x1800},
  { (subindex*)SlaveOD_Index1801,sizeof(SlaveOD_Index1801)/sizeof(SlaveOD_Index1801[0]), 0x1801},
  { (subindex*)SlaveOD_Index1802,sizeof(SlaveOD_Index1802)/sizeof(SlaveOD_Index1802[0]), 0x1802},
  { (subindex*)SlaveOD_Index1803,sizeof(SlaveOD_Index1803)/sizeof(SlaveOD_Index1803[0]), 0x1803},
  { (subindex*)SlaveOD_Index1A00,sizeof(SlaveOD_Index1A00)/sizeof(SlaveOD_Index1A00[0]), 0x1A00},
  { (subindex*)SlaveOD_Index1A01,sizeof(SlaveOD_Index1A01)/sizeof(SlaveOD_Index1A01[0]), 0x1A01},
  { (subindex*)SlaveOD_Index1A02,sizeof(SlaveOD_Index1A02)/sizeof(SlaveOD_Index1A02[0]), 0x1A02},
  { (subindex*)SlaveOD_Index1A03,sizeof(SlaveOD_Index1A03)/sizeof(SlaveOD_Index1A03[0]), 0x1A03},
  { (subindex*)SlaveOD_Index603F,sizeof(SlaveOD_Index603F)/sizeof(SlaveOD_Index603F[0]), 0x603F},
  { (subindex*)SlaveOD_Index6040,sizeof(SlaveOD_Index6040)/sizeof(SlaveOD_Index6040[0]), 0x6040},
  { (subindex*)SlaveOD_Index6041,sizeof(SlaveOD_Index6041)/sizeof(SlaveOD_Index6041[0]), 0x6041},
  { (subindex*)SlaveOD_Index605A,sizeof(SlaveOD_Index605A)/sizeof(SlaveOD_Index605A[0]), 0x605A},
  { (subindex*)SlaveOD_Index6060,sizeof(SlaveOD_Index6060)/sizeof(SlaveOD_Index6060[0]), 0x6060},
  { (subindex*)SlaveOD_Index6061,sizeof(SlaveOD_Index6061)/sizeof(SlaveOD_Index6061[0]), 0x6061},
  { (subindex*)SlaveOD_Index6062,sizeof(SlaveOD_Index6062)/sizeof(SlaveOD_Index6062[0]), 0x6062},
  { (subindex*)SlaveOD_Index6063,sizeof(SlaveOD_Index6063)/sizeof(SlaveOD_Index6063[0]), 0x6063},
  { (subindex*)SlaveOD_Index6064,sizeof(SlaveOD_Index6064)/sizeof(SlaveOD_Index6064[0]), 0x6064},
  { (subindex*)SlaveOD_Index6065,sizeof(SlaveOD_Index6065)/sizeof(SlaveOD_Index6065[0]), 0x6065},
  { (subindex*)SlaveOD_Index6066,sizeof(SlaveOD_Index6066)/sizeof(SlaveOD_Index6066[0]), 0x6066},
  { (subindex*)SlaveOD_Index6067,sizeof(SlaveOD_Index6067)/sizeof(SlaveOD_Index6067[0]), 0x6067},
  { (subindex*)SlaveOD_Index6068,sizeof(SlaveOD_Index6068)/sizeof(SlaveOD_Index6068[0]), 0x6068},
  { (subindex*)SlaveOD_Index6069,sizeof(SlaveOD_Index6069)/sizeof(SlaveOD_Index6069[0]), 0x6069},
  { (subindex*)SlaveOD_Index606B,sizeof(SlaveOD_Index606B)/sizeof(SlaveOD_Index606B[0]), 0x606B},
  { (subindex*)SlaveOD_Index606C,sizeof(SlaveOD_Index606C)/sizeof(SlaveOD_Index606C[0]), 0x606C},
  { (subindex*)SlaveOD_Index606D,sizeof(SlaveOD_Index606D)/sizeof(SlaveOD_Index606D[0]), 0x606D},
  { (subindex*)SlaveOD_Index606E,sizeof(SlaveOD_Index606E)/sizeof(SlaveOD_Index606E[0]), 0x606E},
  { (subindex*)SlaveOD_Index606F,sizeof(SlaveOD_Index606F)/sizeof(SlaveOD_Index606F[0]), 0x606F},
  { (subindex*)SlaveOD_Index6070,sizeof(SlaveOD_Index6070)/sizeof(SlaveOD_Index6070[0]), 0x6070},
  { (subindex*)SlaveOD_Index6071,sizeof(SlaveOD_Index6071)/sizeof(SlaveOD_Index6071[0]), 0x6071},
  { (subindex*)SlaveOD_Index6072,sizeof(SlaveOD_Index6072)/sizeof(SlaveOD_Index6072[0]), 0x6072},
  { (subindex*)SlaveOD_Index6073,sizeof(SlaveOD_Index6073)/sizeof(SlaveOD_Index6073[0]), 0x6073},
  { (subindex*)SlaveOD_Index6074,sizeof(SlaveOD_Index6074)/sizeof(SlaveOD_Index6074[0]), 0x6074},
  { (subindex*)SlaveOD_Index6075,sizeof(SlaveOD_Index6075)/sizeof(SlaveOD_Index6075[0]), 0x6075},
  { (subindex*)SlaveOD_Index6076,sizeof(SlaveOD_Index6076)/sizeof(SlaveOD_Index6076[0]), 0x6076},
  { (subindex*)SlaveOD_Index6077,sizeof(SlaveOD_Index6077)/sizeof(SlaveOD_Index6077[0]), 0x6077},
  { (subindex*)SlaveOD_Index6078,sizeof(SlaveOD_Index6078)/sizeof(SlaveOD_Index6078[0]), 0x6078},
  { (subindex*)SlaveOD_Index6079,sizeof(SlaveOD_Index6079)/sizeof(SlaveOD_Index6079[0]), 0x6079},
  { (subindex*)SlaveOD_Index607A,sizeof(SlaveOD_Index607A)/sizeof(SlaveOD_Index607A[0]), 0x607A},
  { (subindex*)SlaveOD_Index607B,sizeof(SlaveOD_Index607B)/sizeof(SlaveOD_Index607B[0]), 0x607B},
  { (subindex*)SlaveOD_Index607C,sizeof(SlaveOD_Index607C)/sizeof(SlaveOD_Index607C[0]), 0x607C},
  { (subindex*)SlaveOD_Index607D,sizeof(SlaveOD_Index607D)/sizeof(SlaveOD_Index607D[0]), 0x607D},
  { (subindex*)SlaveOD_Index607E,sizeof(SlaveOD_Index607E)/sizeof(SlaveOD_Index607E[0]), 0x607E},
  { (subindex*)SlaveOD_Index607F,sizeof(SlaveOD_Index607F)/sizeof(SlaveOD_Index607F[0]), 0x607F},
  { (subindex*)SlaveOD_Index6080,sizeof(SlaveOD_Index6080)/sizeof(SlaveOD_Index6080[0]), 0x6080},
  { (subindex*)SlaveOD_Index6081,sizeof(SlaveOD_Index6081)/sizeof(SlaveOD_Index6081[0]), 0x6081},
  { (subindex*)SlaveOD_Index6083,sizeof(SlaveOD_Index6083)/sizeof(SlaveOD_Index6083[0]), 0x6083},
  { (subindex*)SlaveOD_Index6084,sizeof(SlaveOD_Index6084)/sizeof(SlaveOD_Index6084[0]), 0x6084},
  { (subindex*)SlaveOD_Index6085,sizeof(SlaveOD_Index6085)/sizeof(SlaveOD_Index6085[0]), 0x6085},
  { (subindex*)SlaveOD_Index6086,sizeof(SlaveOD_Index6086)/sizeof(SlaveOD_Index6086[0]), 0x6086},
  { (subindex*)SlaveOD_Index6087,sizeof(SlaveOD_Index6087)/sizeof(SlaveOD_Index6087[0]), 0x6087},
  { (subindex*)SlaveOD_Index6089,sizeof(SlaveOD_Index6089)/sizeof(SlaveOD_Index6089[0]), 0x6089},
  { (subindex*)SlaveOD_Index608A,sizeof(SlaveOD_Index608A)/sizeof(SlaveOD_Index608A[0]), 0x608A},
  { (subindex*)SlaveOD_Index608B,sizeof(SlaveOD_Index608B)/sizeof(SlaveOD_Index608B[0]), 0x608B},
  { (subindex*)SlaveOD_Index608C,sizeof(SlaveOD_Index608C)/sizeof(SlaveOD_Index608C[0]), 0x608C},
  { (subindex*)SlaveOD_Index608D,sizeof(SlaveOD_Index608D)/sizeof(SlaveOD_Index608D[0]), 0x608D},
  { (subindex*)SlaveOD_Index608E,sizeof(SlaveOD_Index608E)/sizeof(SlaveOD_Index608E[0]), 0x608E},
  { (subindex*)SlaveOD_Index608F,sizeof(SlaveOD_Index608F)/sizeof(SlaveOD_Index608F[0]), 0x608F},
  { (subindex*)SlaveOD_Index6091,sizeof(SlaveOD_Index6091)/sizeof(SlaveOD_Index6091[0]), 0x6091},
  { (subindex*)SlaveOD_Index6098,sizeof(SlaveOD_Index6098)/sizeof(SlaveOD_Index6098[0]), 0x6098},
  { (subindex*)SlaveOD_Index6099,sizeof(SlaveOD_Index6099)/sizeof(SlaveOD_Index6099[0]), 0x6099},
  { (subindex*)SlaveOD_Index609A,sizeof(SlaveOD_Index609A)/sizeof(SlaveOD_Index609A[0]), 0x609A},
  { (subindex*)SlaveOD_Index60B0,sizeof(SlaveOD_Index60B0)/sizeof(SlaveOD_Index60B0[0]), 0x60B0},
  { (subindex*)SlaveOD_Index60B1,sizeof(SlaveOD_Index60B1)/sizeof(SlaveOD_Index60B1[0]), 0x60B1},
  { (subindex*)SlaveOD_Index60B2,sizeof(SlaveOD_Index60B2)/sizeof(SlaveOD_Index60B2[0]), 0x60B2},
  { (subindex*)SlaveOD_Index60C2,sizeof(SlaveOD_Index60C2)/sizeof(SlaveOD_Index60C2[0]), 0x60C2},
  { (subindex*)SlaveOD_Index60C5,sizeof(SlaveOD_Index60C5)/sizeof(SlaveOD_Index60C5[0]), 0x60C5},
  { (subindex*)SlaveOD_Index60C6,sizeof(SlaveOD_Index60C6)/sizeof(SlaveOD_Index60C6[0]), 0x60C6},
  { (subindex*)SlaveOD_Index60F4,sizeof(SlaveOD_Index60F4)/sizeof(SlaveOD_Index60F4[0]), 0x60F4},
  { (subindex*)SlaveOD_Index60F6,sizeof(SlaveOD_Index60F6)/sizeof(SlaveOD_Index60F6[0]), 0x60F6},
  { (subindex*)SlaveOD_Index60F9,sizeof(SlaveOD_Index60F9)/sizeof(SlaveOD_Index60F9[0]), 0x60F9},
  { (subindex*)SlaveOD_Index60FB,sizeof(SlaveOD_Index60FB)/sizeof(SlaveOD_Index60FB[0]), 0x60FB},
  { (subindex*)SlaveOD_Index60FD,sizeof(SlaveOD_Index60FD)/sizeof(SlaveOD_Index60FD[0]), 0x60FD},
  { (subindex*)SlaveOD_Index60FE,sizeof(SlaveOD_Index60FE)/sizeof(SlaveOD_Index60FE[0]), 0x60FE},
  { (subindex*)SlaveOD_Index60FF,sizeof(SlaveOD_Index60FF)/sizeof(SlaveOD_Index60FF[0]), 0x60FF},
  { (subindex*)SlaveOD_Index6402,sizeof(SlaveOD_Index6402)/sizeof(SlaveOD_Index6402[0]), 0x6402},
  { (subindex*)SlaveOD_Index6410,sizeof(SlaveOD_Index6410)/sizeof(SlaveOD_Index6410[0]), 0x6410},
  { (subindex*)SlaveOD_Index6502,sizeof(SlaveOD_Index6502)/sizeof(SlaveOD_Index6502[0]), 0x6502},
};

const indextable * SlaveOD_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
        OD_Write_Callback = NULL;
        OD_Read_Callback = NULL;

	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1008: i = 2;break;
		case 0x1016: i = 3;break;
		case 0x1017: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1200: i = 6;break;
		case 0x1400: i = 7;break;
		case 0x1401: i = 8;break;
		case 0x1402: i = 9;break;
		case 0x1403: i = 10;break;
		case 0x1600: i = 11;break;
		case 0x1601: i = 12;break;
		case 0x1602: i = 13;break;
		case 0x1603: i = 14;break;
		case 0x1800: i = 15;break;
		case 0x1801: i = 16;break;
		case 0x1802: i = 17;break;
		case 0x1803: i = 18;break;
		case 0x1A00: i = 19;break;
		case 0x1A01: i = 20;break;
		case 0x1A02: i = 21;break;
		case 0x1A03: i = 22;break;
		case 0x603F: i = 23;break;
		case 0x6040: i = 24;break;
		case 0x6041: i = 25;break;
		case 0x605A: i = 26;break;
		case 0x6060: i = 27;break;
		case 0x6061: i = 28;break;
		case 0x6062: i = 29;break;
		case 0x6063: i = 30;break;
		case 0x6064: i = 31;break;
		case 0x6065: i = 32;break;
		case 0x6066: i = 33;break;
		case 0x6067: i = 34;break;
		case 0x6068: i = 35;break;
		case 0x6069: i = 36;break;
		case 0x606B: i = 37;break;
		case 0x606C: i = 38;break;
		case 0x606D: i = 39;break;
		case 0x606E: i = 40;break;
		case 0x606F: i = 41;break;
		case 0x6070: i = 42;break;
		case 0x6071: i = 43;break;
		case 0x6072: i = 44;break;
		case 0x6073: i = 45;break;
		case 0x6074: i = 46;break;
		case 0x6075: i = 47;break;
		case 0x6076: i = 48;break;
		case 0x6077: i = 49;break;
		case 0x6078: i = 50;break;
		case 0x6079: i = 51;break;
		case 0x607A: i = 52;break;
		case 0x607B: i = 53;break;
		case 0x607C: i = 54;break;
		case 0x607D: i = 55;break;
		case 0x607E: i = 56;break;
		case 0x607F: i = 57;break;
		case 0x6080: i = 58;break;
		case 0x6081: i = 59;break;
		case 0x6083: i = 60;break;
		case 0x6084: i = 61;break;
		case 0x6085: i = 62;break;
		case 0x6086: i = 63;break;
		case 0x6087: i = 64;break;
		case 0x6089: i = 65;break;
		case 0x608A: i = 66;break;
		case 0x608B: i = 67;break;
		case 0x608C: i = 68;break;
		case 0x608D: i = 69;break;
		case 0x608E: i = 70;break;
		case 0x608F: i = 71;break;
		case 0x6091: i = 72;break;
		case 0x6098: i = 73;break;
		case 0x6099: i = 74;break;
		case 0x609A: i = 75;break;
		case 0x60B0: i = 76;break;
		case 0x60B1: i = 77;break;
		case 0x60B2: i = 78;break;
		case 0x60C2: i = 79;break;
		case 0x60C5: i = 80;break;
		case 0x60C6: i = 81;break;
		case 0x60F4: i = 82;break;
		case 0x60F6: i = 83;break;
		case 0x60F9: i = 84;break;
		case 0x60FB: i = 85;break;
		case 0x60FD: i = 86;break;
		case 0x60FE: i = 87;break;
		case 0x60FF: i = 88;break;
		case 0x6402: i = 89;break;
		case 0x6410: i = 90;break;
		case 0x6502: i = 91;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}

	*errorCode = OD_SUCCESSFUL;
	if (wIndex >= 0x2000)
    {
        extern UNS32 SlaveOD_Read_Callback(uint16_t     index, uint8_t subindex, void *data);
        extern UNS32 SlaveOD_Write_Callback(uint16_t index, uint8_t subindex, void *data);
        OD_Write_Callback = SlaveOD_Write_Callback;
        OD_Read_Callback = SlaveOD_Read_Callback;
    }
	return &SlaveOD_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status SlaveOD_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index SlaveOD_firstIndex = {
  6, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */
  11, /* PDO_RCV_MAP */
  15, /* PDO_TRS */
  19 /* PDO_TRS_MAP */
};

const quick_index SlaveOD_lastIndex = {
  6, /* SDO_SVR */
  0, /* SDO_CLT */
  10, /* PDO_RCV */
  14, /* PDO_RCV_MAP */
  18, /* PDO_TRS */
  22 /* PDO_TRS_MAP */
};

const UNS16 SlaveOD_ObjdictSize = sizeof(SlaveOD_objdict)/sizeof(SlaveOD_objdict[0]); 

CO_Data SlaveOD_Data = CANOPEN_NODE_DATA_INITIALIZER(SlaveOD);

